files:
  - source: /docs/Concepts/*.md
    translation: /website/translated_docs/%locale%/%original_file_name%
  - source: /docs/assets/en/**/*.png
    translation: /docs/assets/%two_letters_code%/**/%original_file_name%
