files:
  - source: /docs/**/*
    ignore:
      - /docs/preprocessing.conf
      - /docs/commands-legacy/*.*
      - /docs/WritePro/commands-legacy/*.*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /i18n/en/docusaurus-plugin-content-docs/*.json
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/%original_file_name%
  - source: /versioned_docs/**/*
    ignore:
      - /versioned_docs/**/preprocessing.conf
      - /versioned_docs/**/commands-legacy/*.*
      - /versioned_docs/**/WritePro/commands-legacy/*.*
      - /versioned_docs/version-18/*.*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
  - source: /i18n/en/docusaurus-theme-classic/*.json
    translation: /i18n/%two_letters_code%/docusaurus-theme-classic/%original_file_name%
  - source: /i18n/en/*.json
    translation: /i18n/%two_letters_code%/%original_file_name%
