module.exports =
{
  docs: [
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
        title: "Getting Started",
        slug: "/category/getting-started",
        keywords: [
          "start"
        ],
        image: "/img/docusaurus.png"
      },
      items: [
        "GettingStarted/installation",
        "Project/overview",
        "Notes/updates"
      ]
    },
    {
      type: "category",
      label: "Project & IDE",
      link: {
        type: "generated-index",
        title: "Project & IDE",
        slug: "/category/project-ide",
        keywords: [
          "ide"
        ],
        image: "/img/docusaurus.png"
      },
      items: [
        "GettingStarted/creating",
        "Project/architecture",
        {
          type: "category",
          label: "Dababase structure",
          items: [
            "Develop/field-properties",
            "Develop-legacy/triggers"
          ]
        },
        {
          type: "category",
          label: "Code & Methods",
          items: [
            "Project/code-overview",
            "code-editor/write-class-method",
            "Project/project-method-properties",
            "Project/documentation"
          ]
        },
          "Project/components",
          "Project/compiler",
        {
          type: "category",
          label: "Settings",
          link: {
             type: "doc",
             id: "settings/overview"
          },
          items: [
                "settings/general",
                "settings/interface",
                "settings/compiler",
                "settings/database",
                "settings/backup",
                "settings/client-server",
                "settings/web",
                "settings/sql",
                "settings/php",
                "settings/security",
                "settings/compatibility"
              ]
        },
         "Desktop/building",
          {
           type: "category",
           label: "Debugging",
           link: {
             type: "doc",
             id: "Debugging/basics"
          },
           items: [
                "Debugging/debugger",
                "Debugging/breakpoints",
                "Debugging/debugging-remote"
              ]
          },
                  {
           type: "category",
           label: "Application Preferences",
             items: [
                "Preferences/overview",
                "Preferences/general",
                "Preferences/structure",
                "Preferences/forms",
                "Preferences/methods",
                "Preferences/shortcuts"
              ]
          }
      ] 
    },
    {
      type: "category",
      label: "4D Language",
      link: {
        type: "generated-index",
        title: "4D Language",
        slug: "/category/4d-language",
        keywords: [
          "language","orda"
        ],
        image: "/img/docusaurus.png"
      },
      items: [
        {
          type: "category",
          label: "Concepts",
          items: [
            "Concepts/about",
            "Concepts/quick-tour",
            "Concepts/operators",
            {
              type: "category",
              label: "Data Types",
              link: {
                type: "doc",
                id: "Concepts/data-types"
              },
              items: [
                "Concepts/blob",
                "Concepts/boolean",
                "Concepts/collection",
                "Concepts/date",
                "Concepts/null-undefined",
                "Concepts/number",
                "Concepts/object",
                "Concepts/picture",
                "Concepts/pointer",
                "Concepts/string",
                "Concepts/time",
                "Concepts/variant"
              ]
            },
            "Concepts/variables",
            "Concepts/arrays",
            "Concepts/methods",
            "Concepts/parameters",
            "Concepts/shared",
            "Concepts/classes",
            "Concepts/control-flow",
            "Concepts/error-handling",
            "Concepts/interpreted-compiled",
            "Concepts/components",
            "Concepts/plug-ins",
            "Concepts/identifiers",
            "Concepts/paths"
          ]
        },
        "commands/command-index",
        {
          type: "category",
          label: "Commands by theme",
          link: {
            type: "generated-index",
            title: "Commands by theme",
            slug: "/category/commands",
            image: "/img/docusaurus.png"
          },
          items: [
          {
            type: "autogenerated",
            dirName: "commands/theme", // Generate sidebar slice from docs/theme
          },
        ],
        }, 
        {
          type: "category",
          label: "Classes",
          items: [
            "API/BlobClass",
            "API/ClassClass",
            "API/CollectionClass",
            "API/CryptoKeyClass",
            "API/DataClassClass",
            "API/DataStoreClass",
            "API/EmailObjectClass",
            "API/EntityClass",
            "API/EntitySelectionClass",
            "API/FileClass",
            "API/FileHandleClass",
            "API/FolderClass",
            "API/FunctionClass",
            "API/HTTPAgentClass",
            "API/HTTPRequestClass",
            "API/IMAPTransporterClass",
            "API/IncomingMessageClass",
            "API/MailAttachmentClass",
            "API/OutgoingMessageClass",
            "API/POP3TransporterClass",
            "API/SessionClass",
            "API/SignalClass",
            "API/SMTPTransporterClass",
            "API/SystemWorkerClass",
            "API/TCPConnectionClass",
            "API/TCPEventClass",
            "API/TCPListenerClass",
            "API/UDPEventClass",
            "API/UDPSocketClass",
            "API/VectorClass",
            "API/WebFormClass",
            "API/WebFormItemClass",
            "API/WebServerClass",
            "API/WebSocketClass",
            "API/WebSocketConnectionClass",
            "API/WebSocketServerClass",
            "API/ZipArchiveClass",
            "API/ZipFileClass",
            "API/ZipFolderClass"
          ],
          link: {
            type: "generated-index",
            title: "Classes",
            description: "List of built-in 4D classes",
            slug: "/category/class-API-reference",
            keywords: [
              "class"
            ],
            image: "/img/docusaurus.png"
          }
        }
      ]
    },
    {
          type: "category",
          label: "Core Development",
          link: {
            type: "generated-index",
            title: "Core Development",
            slug: "/category/core",
            image: "/img/docusaurus.png"
          },
          items: [
            {
              type: "category",
              label: "ORDA",
              link: {
                type: "doc",
                id: "ORDA/overview"
              },
              items: [
                "ORDA/dsmapping",
                "ORDA/ordaClasses",
                "ORDA/entities",
                "ORDA/orda-events",
                "ORDA/global-stamp",
                "ORDA/datastores",
                "ORDA/privileges",
                "ORDA/client-server-optimization",
              "ORDA/glossary"
          ]
        },
        {
          type: "category",
          label: "Processes",
          link: {
            type: "generated-index",
            title: "Processes",
            slug: "/category/processes",
            keywords: [
              "feaprocessestures"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            "Develop/processes",
            "Develop/preemptive-processes"
          ]
        },
        {
          type: "category",
          label: "Database Methods",
          link: {
            type: "generated-index",
            title: "Database Methods",
            slug: "/category/database-methods",
            image: "/img/docusaurus.png"
          },
          items: [
           "commands-legacy/on-backup-shutdown-database-method",
                "commands-legacy/on-backup-startup-database-method",
                "commands-legacy/on-drop-database-method",
                "commands-legacy/on-exit-database-method",
                "commands-legacy/on-host-database-event-database-method",
                "commands-legacy/on-mobile-app-action-database-method",
                "commands-legacy/on-mobile-app-authentication-database-method",
                "commands-legacy/on-rest-authentication-database-method",
                "commands-legacy/on-server-close-connection-database-method",
                "commands-legacy/on-server-open-connection-database-method",
                "commands-legacy/on-server-shutdown-database-method",
                "commands-legacy/on-server-startup-database-method",
                "commands-legacy/on-sql-authentication-database-method",
                "commands-legacy/on-startup-database-method",
                "commands-legacy/on-system-event-database-method",
                "commands-legacy/on-web-authentication-database-method",
                "commands-legacy/on-web-connection-database-method",
                "commands-legacy/on-web-legacy-close-session-database-method"
          ]
        },
        "Develop-legacy/transactions",
        "Develop-legacy/triggers",
        "Tags/transformation-tags",
        "Project/date-time-formats"
      ]
    },
    {
      type: "category",
      label: "Web Applications",
      link: {
        type: "generated-index",
        title: "Web Applications",
        description: "Guides for developing Web applications with 4D",
        keywords: [
          "web applications"
        ],
        image: "/img/docusaurus.png"
      },
      items: [
                {
          type: "link",
          label: "4D Qodly Pro",
          href: "https://developer.qodly.com/docs"
        },
        {
          type: "category",
          label: "Web Server",
          link: {
            type: "doc",
            id: "WebServer/webServer"
          },
          items: [
            "WebServer/gettingStarted",
            "WebServer/webServerConfig",
            "WebServer/webServerAdmin",
            "WebServer/webServerObject",
            "WebServer/templates",
            "WebServer/httpRequests",
            "WebServer/http-request-handler",
            "WebServer/http-rules",
            "WebServer/allowProject",
            "WebServer/errorPages",
            "WebServer/authentication",
            "WebServer/sessions",
            "WebServer/preemptiveWeb"
          ]
        },
        {
          type: "category",
          label: "REST API",
          link: {
            type: "generated-index",
            title: "REST API",
            description: "Exposing your datastore to REST and using the REST API.",
            keywords: [
              "REST server"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            {
              type: "category",
              label: "Exposing your datastore in REST",
              link: {
                type: "generated-index",
                title: "Exposing your datastore in REST",
                description: "Configure your datastore for REST access",
                keywords: [
                  "REST access"
                ],
                image: "/img/docusaurus.png"
              },
              items: [
                "REST/gettingStarted",
                "REST/configuration",
                "REST/authUsers",
                "REST/genInfo",
                "REST/manData",
                "REST/classFunctions",
                "REST/REST_requests"
              ]
            },
            {
              type: "category",
              label: "API (general)",
              link: {
                type: "generated-index",
                title: "API (general)",
                description: "REST API for global information",
                keywords: [
                  "REST API"
                ],
                image: "/img/docusaurus.png"
              },
              items: [
                "REST/catalog",
                "REST/info",
                "REST/singleton",
                "REST/upload"
              ]
            },
            {
              type: "category",
              label: "API (dataClass)",
              link: {
                type: "generated-index",
                title: "API (dataClass)",
                description: "REST API for dataClass.",
                keywords: [
                  "REST API"
                ],
                image: "/img/docusaurus.png"
              },
              items: [
                "REST/dataClass",
                "REST/asArray",
                "REST/atomic_$atonce",
                "REST/attributes",
                "REST/binary",
                "REST/clean",
                "REST/compute",
                "REST/distinct",
                "REST/entityset",
                "REST/expand",
                "REST/filter",
                "REST/format",
                "REST/imageformat",
                "REST/lock",
                "REST/method",
                "REST/orderby",
                "REST/querypath",
                "REST/queryplan",
                "REST/savedfilter",
                "REST/savedorderby",
                "REST/skip",
                "REST/timeout",
                "REST/top_$limit",
                "REST/version"
              ]
            }
          ]
        }
      ]
    },
    {
      type: "category",
      label: "Desktop Applications",
      link: {
        type: "generated-index",
        title: "Desktop Applications",
        description: "Guides for developing Desktop applications with 4D",
        keywords: [
          "desktop applications"
        ],
        image: "/img/docusaurus.png"
      },
      items: [
        {
          type: "doc",
          label: "Client/Server",
          id: "Desktop/clientServer"
        },
        {
          type: "category",
          label: "Forms",
          link: {
            type: "doc",
            id: "FormEditor/forms"
          },
          items: [
            "FormEditor/stylesheets",
            "FormEditor/pictures",
            {
              type: "category",
              label: "Form Editor",
              link: {
                type: "doc",
                id: "FormEditor/formEditor"
              },
              items: [
                "FormEditor/macros",
                "FormEditor/objectLibrary"
              ]
            },
            {
              type: "category",
              label: "Form Properties",
              link: {
                type: "doc",
                id: "FormEditor/jsonReference"
              },
              items: [
                "FormEditor/action",
                "FormEditor/propertiesForm",
                "FormEditor/formSize",
                "FormEditor/markers",
                "FormEditor/menu",
                "FormEditor/print",
                "FormEditor/windowSize"
              ]
            },
            {
              type: "category",
              label: "Form Objects",
              link: {
                type: "doc",
                id: "FormObjects/formObjectsOverview"
              },
              items: [
                "FormObjects/buttonOverview",
                "FormObjects/buttonGridOverview",
                "FormObjects/checkboxOverview",
                "FormObjects/comboBoxOverview",
                "FormObjects/dropdownListOverview",
                "FormObjects/groupBox",
                "FormObjects/inputOverview",
                "FormObjects/listOverview",
                "FormObjects/listboxOverview",
                "FormObjects/pictureButtonOverview",
                "FormObjects/picturePopupMenuOverview",
                "FormObjects/pluginAreaOverview",
                "FormObjects/progressIndicator",
                "FormObjects/radiobuttonOverview",
                "FormObjects/ruler",
                "FormObjects/shapesOverview",
                "FormObjects/spinner",
                "FormObjects/splitters",
                "FormObjects/staticPicture",
                "FormObjects/stepper",
                "FormObjects/subformOverview",
                "FormObjects/tabControl",
                "FormObjects/text",
                "FormObjects/webAreaOverview",
                "FormObjects/viewProAreaOverview",
                "FormObjects/writeProAreaOverview"
              ]
            },
            {
              type: "category",
              label: "Form Object Properties",
              link: {
                type: "doc",
                id: "FormObjects/propertiesReference"
              },
              items: [
                "FormObjects/propertiesAction",
                "FormObjects/propertiesAnimation",
                "FormObjects/propertiesAppearance",
                "FormObjects/propertiesBackgroundAndBorder",
                "FormObjects/propertiesCoordinatesAndSizing",
                "FormObjects/propertiesCrop",
                "FormObjects/propertiesDataSource",
                "FormObjects/propertiesDisplay",
                "FormObjects/propertiesEntry",
                "FormObjects/propertiesFooters",
                "FormObjects/propertiesGridlines",
                "FormObjects/propertiesHeaders",
                "FormObjects/propertiesHelp",
                "FormObjects/propertiesHierarchy",
                "FormObjects/propertiesListBox",
                "FormObjects/propertiesObject",
                "FormObjects/propertiesPicture",
                "FormObjects/propertiesPlugIns",
                "FormObjects/propertiesPrint",
                "FormObjects/propertiesRangeOfValues",
                "FormObjects/propertiesResizingOptions",
                "FormObjects/propertiesScale",
                "FormObjects/propertiesSubform",
                "FormObjects/propertiesText",
                "FormObjects/propertiesTextAndPicture",
                "FormObjects/propertiesWebArea"
              ]
            },
            {
              type: "category",
              label: "Form Events",
              link: {
                type: "doc",
                id: "Events/overview"
              },
              items: [
                "Events/onActivate",
                "Events/onAfterEdit",
                "Events/onAfterKeystroke",
                "Events/onAfterSort",
                "Events/onAlternativeClick",
                "Events/onBeforeDataEntry",
                "Events/onBeforeKeystroke",
                "Events/onBeginDragOver",
                "Events/onBeginUrlLoading",
                "Events/onBoundVariableChange",
                "Events/onClicked",
                "Events/onCloseBox",
                "Events/onCloseDetail",
                "Events/onCollapse",
                "Events/onColumnMoved",
                "Events/onColumnResize",
                "Events/onDataChange",
                "Events/onDeactivate",
                "Events/onDeleteAction",
                "Events/onDisplayDetail",
                "Events/onDoubleClicked",
                "Events/onDragOver",
                "Events/onDrop",
                "Events/onEndUrlLoading",
                "Events/onExpand",
                "Events/onFooterClick",
                "Events/onGettingFocus",
                "Events/onHeader",
                "Events/onHeaderClick",
                "Events/onLoad",
                "Events/onLoadRecord",
                "Events/onLongClick",
                "Events/onLosingFocus",
                "Events/onMenuSelected",
                "Events/onMouseEnter",
                "Events/onMouseLeave",
                "Events/onMouseMove",
                "Events/onMouseUp",
                "Events/onOpenDetail",
                "Events/onOpenExternalLink",
                "Events/onOutsideCall",
                "Events/onPageChange",
                "Events/onPlugInArea",
                "Events/onPrintingBreak",
                "Events/onPrintingDetail",
                "Events/onPrintingFooter",
                "Events/onResize",
                "Events/onRowMoved",
                "Events/onRowResize",
                "Events/onScroll",
                "Events/onSelectionChange",
                "Events/onTimer",
                "Events/onUnload",
                "Events/onUrlFiltering",
                "Events/onUrlLoadingError",
                "Events/onUrlResourceLoading",
                "Events/onValidate",
                "Events/onVpRangeChanged",
                "Events/onVpReady",
                "Events/onWindowOpeningDenied"
              ]
            }
          ]
        },
         {
          type: "doc",
          label: "Labels",
          id: "Desktop/labels"
        },
        {
          type: "category",
          label: "Menus",
          link: {
            type: "doc",
            id: "Menus/overview"
          },
          items: [
            "Menus/creating",
            "Menus/properties",
            "Menus/bars",
            "Menus/sdi"
          ]
        },
        {
          type: "category",
          label: "Access Rights",
          link: {
            type: "generated-index",
            title: "Access Rights",
            description: "Access control and user privileges for desktop applications.",
            slug: "/category/access-rights",
            keywords: [
              "access rights",
              "user settings",
              "permissions"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            "Users/overview",
            "Users/editing"
          ]
        }
      ]
    },
    {
      type: "category",
      label: "Administration",
      link: {
        type: "generated-index",
        title: "Administration",
        description: "How to monitor your 4D applications",
        keywords: [
          "administration"
        ],
        image: "/img/docusaurus.png"
      },
      items: [
        {
          type: "category",
          label: "4D Server Administration Window",
          link: {
            type: "doc",
            id: "ServerWindow/overview"
          },
          items: [
            "ServerWindow/monitor",
            "ServerWindow/users",
            "ServerWindow/processes",
            "ServerWindow/maintenance",
            "ServerWindow/application-server",
            "ServerWindow/sql-server",
            "ServerWindow/http-server",
            "ServerWindow/real-time-monitor",
            "ServerWindow/remote-admin"
          ]
        },
        {
          type: "category",
          label: "Web Administration",
          link: {
            type: "generated-index",
            title: "Web Administration",
            description: "4D web tools for administrating and monitoring your applications.",
            slug: "/category/web-administration",
            keywords: [
              "web administration"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            "Admin/webAdmin",
            "Admin/dataExplorer"
          ]
        },
        {
          type: "doc",
          label: "Command Line Interface",
          id: "Admin/cli"
        },
        {
          type: "doc",
          label: "TLS Protocol",
          id: "Admin/tls"
        },
        {
          type: "doc",
          label: "Licenses",
          id: "Admin/licenses"
        },
        {
          type: "doc",
          label: "Log Files",
          id: "Debugging/debugLogFiles"
        },
        {
          type: "category",
          label: "MSC",
          link: {
            type: "doc",
            id: "MSC/overview"
          },
          items: [
            "MSC/information",
            "MSC/analysis",
            "MSC/verify",
            "MSC/backup",
            "MSC/compact",
            "MSC/rollback",
            "MSC/restore",
            "MSC/repair",
            "MSC/encrypt"
          ]
        },
        {
          type: "category",
          label: "Backup and Restore",
          link: {
            type: "doc",
            id: "Backup/overview"
          },
          items: [
            "Backup/backup",
            "Backup/settings",
            "Backup/log",
            "Backup/restore"
          ]
        },
        {
          type: "doc",
          label: "Data Collection",
          id: "Admin/data-collect"
        }
      ]
    },
    {
      type: "category",
      label: "Extensions",
      link: {
        type: "generated-index",
        title: "Extensions",
        slug: "/category/extensions",
        keywords: [
          "component, extension, plug-in"],
        image: "/img/docusaurus.png"
      },
      items: [
        {
            type: "category",
            label: "Extending 4D applications",
            link: {
              type: "doc",
              id: "Extensions/overview"
            },
            items: [
             "Extensions/develop-components",
              "Extensions/develop-plug-ins"
                  ]
        },
        {
          type: "link",
          label: "4D Qodly Pro",
          href: "https://developer.4d.com/qodly/"
        },        
        {
          type: "category",
          label: "4D View Pro",
          link: {
            type: "generated-index",
            title: "4D View Pro",
            slug: "/category/4d-view-pro",
            keywords: [
              "4D View Pro"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            "ViewPro/getting-started",
            "ViewPro/configuring",
            "ViewPro/formulas",
            "ViewPro/classes",
            "ViewPro/advanced-programming",
            {
              type: "category",
              label: "Commands",
              link: {
                type: "doc",
                id: "ViewPro/commands"
              },
              items: [
                {
                  type: "category",
                  label: "A",
                  link: {
                    type: "generated-index",
                    title: "A",
                    slug: "/commands-legacy/A"
                  },
                  items: [
                    "ViewPro/commands/vp-add-formula-name",
                    "ViewPro/commands/vp-add-range-name",
                    "ViewPro/commands/vp-add-selection",
                    "ViewPro/commands/vp-add-sheet",
                    "ViewPro/commands/vp-add-span",
                    "ViewPro/commands/vp-add-stylesheet",
                    "ViewPro/commands/vp-all"
                  ]
                },
                {
                  type: "category",
                  label: "C",
                  link: {
                    type: "generated-index",
                    title: "C",
                    slug: "/commands-legacy/C"
                  },
                  items: [
                    "ViewPro/commands/vp-cell",
                    "ViewPro/commands/vp-cells",
                    "ViewPro/commands/vp-column",
                    "ViewPro/commands/vp-column-autofit",
                    "ViewPro/commands/vp-combine-ranges",
                    "ViewPro/commands/vp-convert-from-4d-view",
                    "ViewPro/commands/vp-convert-to-picture",
                    "ViewPro/commands/vp-copy-to-object",
                    "ViewPro/commands/vp-create-table"
                  ]
                },
                {
                  type: "category",
                  label: "D",
                  link: {
                    type: "generated-index",
                    title: "D",
                    slug: "/commands-legacy/D"
                  },
                  items: [
                    "ViewPro/commands/vp-delete-columns",
                    "ViewPro/commands/vp-delete-rows"
                  ]
                },
                {
                  type: "category",
                  label: "E",
                  link: {
                    type: "generated-index",
                    title: "E",
                    slug: "/commands-legacy/E"
                  },
                  items: [
                    "ViewPro/commands/vp-export-document",
                    "ViewPro/commands/vp-export-to-blob",
                    "ViewPro/commands/vp-export-to-object"
                  ]
                },
                {
                  type: "category",
                  label: "F",
                  link: {
                    type: "generated-index",
                    title: "F",
                    slug: "/commands-legacy/F"
                  },
                  items: [
                    "ViewPro/commands/vp-find",
                    "ViewPro/commands/vp-find-table",
                    "ViewPro/commands/vp-flush-commands",
                    "ViewPro/commands/vp-font-to-object"
                  ]
                },
                {
                  type: "category",
                  label: "G",
                  link: {
                    type: "generated-index",
                    title: "G",
                    slug: "/commands-legacy/G"
                  },
                  items: [
                    "ViewPro/commands/vp-get-active-cell",
                    "ViewPro/commands/vp-get-binding-path",
                    "ViewPro/commands/vp-get-cell-style",
                    "ViewPro/commands/vp-get-column-attributes",
                    "ViewPro/commands/vp-get-column-count",
                    "ViewPro/commands/vp-get-current-sheet",
                    "ViewPro/commands/vp-get-data-context",
                    "ViewPro/commands/vp-get-default-style",
                    "ViewPro/commands/vp-get-formula",
                    "ViewPro/commands/vp-get-formula-by-name",
                    "ViewPro/commands/vp-get-formulas",
                    "ViewPro/commands/vp-get-frozen-panes",
                    "ViewPro/commands/vp-get-names",
                    "ViewPro/commands/vp-get-print-info",
                    "ViewPro/commands/vp-get-row-attributes",
                    "ViewPro/commands/vp-get-row-count",
                    "ViewPro/commands/vp-get-selection",
                    "ViewPro/commands/vp-get-sheet-count",
                    "ViewPro/commands/vp-get-sheet-index",
                    "ViewPro/commands/vp-get-sheet-name",
                    "ViewPro/commands/vp-get-sheet-options",
                    "ViewPro/commands/vp-get-show-print-lines",
                    "ViewPro/commands/vp-get-spans",
                    "ViewPro/commands/vp-get-stylesheet",
                    "ViewPro/commands/vp-get-stylesheets",
                    "ViewPro/commands/vp-get-table-column-attributes",
                    "ViewPro/commands/vp-get-table-column-index",
                    "ViewPro/commands/vp-get-table-dirty-rows",
                    "ViewPro/commands/vp-get-table-range",
                    "ViewPro/commands/vp-get-table-theme",
                    "ViewPro/commands/vp-get-tables",
                    "ViewPro/commands/vp-get-value",
                    "ViewPro/commands/vp-get-values",
                    "ViewPro/commands/vp-get-workbook-options"
                  ]
                },
                {
                  type: "category",
                  label: "I",
                  link: {
                    type: "generated-index",
                    title: "I",
                    slug: "/commands-legacy/I"
                  },
                  items: [
                    "ViewPro/commands/vp-import-document",
                    "ViewPro/commands/vp-import-from-blob",
                    "ViewPro/commands/vp-import-from-object",
                    "ViewPro/commands/vp-insert-columns",
                    "ViewPro/commands/vp-insert-rows",
                    "ViewPro/commands/vp-insert-table-columns",
                    "ViewPro/commands/vp-insert-table-rows"
                  ]
                },
                {
                  type: "category",
                  label: "M",
                  link: {
                    type: "generated-index",
                    title: "M",
                    slug: "/commands-legacy/M"
                  },
                  items: [
                    "ViewPro/commands/vp-move-cells"
                  ]
                },
                {
                  type: "category",
                  label: "N",
                  link: {
                    type: "generated-index",
                    title: "N",
                    slug: "/commands-legacy/N"
                  },
                  items: [
                    "ViewPro/commands/vp-name",
                    "ViewPro/commands/vp-new-document"
                  ]
                },
                {
                  type: "category",
                  label: "O",
                  link: {
                    type: "generated-index",
                    title: "O",
                    slug: "/commands-legacy/O"
                  },
                  items: [
                    "ViewPro/commands/vp-object-to-font"
                  ]
                },
                {
                  type: "category",
                  label: "P",
                  link: {
                    type: "generated-index",
                    title: "P",
                    slug: "/commands-legacy/P"
                  },
                  items: [
                    "ViewPro/commands/vp-paste-from-object",
                    "ViewPro/commands/vp-print"
                  ]
                },
                {
                  type: "category",
                  label: "R",
                  link: {
                    type: "generated-index",
                    title: "R",
                    slug: "/commands-legacy/R"
                  },
                  items: [
                    "ViewPro/commands/vp-recompute-formulas",
                    "ViewPro/commands/vp-remove-name",
                    "ViewPro/commands/vp-remove-sheet",
                    "ViewPro/commands/vp-remove-span",
                    "ViewPro/commands/vp-remove-stylesheet",
                    "ViewPro/commands/vp-remove-table",
                    "ViewPro/commands/vp-remove-table-columns",
                    "ViewPro/commands/vp-remove-table-rows",
                    "ViewPro/commands/vp-reset-selection",
                    "ViewPro/commands/vp-resize-table",
                    "ViewPro/commands/vp-resume-computing",
                    "ViewPro/commands/vp-row",
                    "ViewPro/commands/vp-row-autofit",
                    "ViewPro/commands/vp-run-offscreen-area"
                  ]
                },
                {
                  type: "category",
                  label: "S",
                  link: {
                    type: "generated-index",
                    title: "S",
                    slug: "/commands-legacy/S"
                  },
                  items: [
                    "ViewPro/commands/vp-set-active-cell",
                    "ViewPro/commands/vp-set-allowed-methods",
                    "ViewPro/commands/vp-set-binding-path",
                    "ViewPro/commands/vp-set-boolean-value",
                    "ViewPro/commands/vp-set-border",
                    "ViewPro/commands/vp-set-cell-style",
                    "ViewPro/commands/vp-set-column-attributes",
                    "ViewPro/commands/vp-set-column-count",
                    "ViewPro/commands/vp-set-current-sheet",
                    "ViewPro/commands/vp-set-custom-functions",
                    "ViewPro/commands/vp-set-data-context",
                    "ViewPro/commands/vp-set-date-time-value",
                    "ViewPro/commands/vp-set-date-value",
                    "ViewPro/commands/vp-set-default-style",
                    "ViewPro/commands/vp-set-field",
                    "ViewPro/commands/vp-set-formula",
                    "ViewPro/commands/vp-set-formulas",
                    "ViewPro/commands/vp-set-frozen-panes",
                    "ViewPro/commands/vp-set-num-value",
                    "ViewPro/commands/vp-set-print-info",
                    "ViewPro/commands/vp-set-row-attributes",
                    "ViewPro/commands/vp-set-row-count",
                    "ViewPro/commands/vp-set-selection",
                    "ViewPro/commands/vp-set-sheet-count",
                    "ViewPro/commands/vp-set-sheet-name",
                    "ViewPro/commands/vp-set-sheet-options",
                    "ViewPro/commands/vp-set-show-print-lines",
                    "ViewPro/commands/vp-set-table-column-attributes",
                    "ViewPro/commands/vp-set-table-theme",
                    "ViewPro/commands/vp-set-text-value",
                    "ViewPro/commands/vp-set-time-value",
                    "ViewPro/commands/vp-set-value",
                    "ViewPro/commands/vp-set-values",
                    "ViewPro/commands/vp-set-workbook-options",
                    "ViewPro/commands/vp-show-cell",
                    "ViewPro/commands/vp-suspend-computing"
                  ]
                }
              ]
            }
          ]
        },
        {
          type: "category",
          label: "4D Write Pro",
          link: {
            type: "generated-index",
            title: "4D Write Pro",
            slug: "/category/4d-write-pro",
            keywords: [
              "4D Write Pro"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            "WritePro/user-legacy/presentation",
            "WritePro/user-legacy/defining-a-4d-write-pro-area",
            "WritePro/writeprointerface",
            "WritePro/user-legacy/4d-write-pro-documents",
            {
                  type: "category",
                  label: "Document Elements",
                  link: {
                    type: "generated-index",
                    title: "Document Elements",
                  },
                  items: [
                    "WritePro/user-legacy/using-a-4d-write-pro-area",
                    "WritePro/user-legacy/handling-pictures",
                    "WritePro/user-legacy/handling-tables",
                    "WritePro/user-legacy/text-boxes",
                    "WritePro/user-legacy/ranges",
                    "WritePro/user-legacy/stylesheets",
                    "WritePro/managing-formulas"
                  ]
            },
            {
                  type: "category",
                  label: "Import and Export",
                  link: {
                    type: "generated-index",
                    title: "Import and Export",
                  },
                  items: [
                    "WritePro/user-legacy/importing-4d-write-documents",
                    "WritePro/user-legacy/importing-and-exporting-in-docx-format",
                    "WritePro/user-legacy/exporting-to-html-and-mime-html-formats",
                    "WritePro/user-legacy/exporting-to-svg-format"
                  ]
            },
            "WritePro/commands-legacy/4d-write-pro-attributes",
            {
              type: "category",
              label: "Commands",
              link: {
                type: "doc",
                id: "WritePro/commands/command-index"
              },
              items: [
                "WritePro/commands/wp-add-picture",
                "WritePro/commands-legacy/wp-bookmark-range",
                "WritePro/commands-legacy/wp-compute-formulas",
                "WritePro/commands-legacy/wp-delete-bookmark",
                "WritePro/commands-legacy/wp-delete-footer",
                "WritePro/commands-legacy/wp-delete-header",
                "WritePro/commands-legacy/wp-delete-picture",
                "WritePro/commands/wp-delete-section",
                "WritePro/commands-legacy/wp-delete-style-sheet",
                "WritePro/commands/wp-delete-subsection",
                "WritePro/commands-legacy/wp-delete-text-box",
                "WritePro/commands/wp-export-document",
                "WritePro/commands/wp-export-variable",
                "WritePro/commands-legacy/wp-find-all",
                "WritePro/commands-legacy/wp-find-next",
                "WritePro/commands-legacy/wp-find-previous",
                "WritePro/commands-legacy/wp-freeze-formulas",
                "WritePro/commands/wp-get-attributes",
                "WritePro/commands-legacy/wp-get-body",
                "WritePro/commands-legacy/wp-get-bookmarks",
                "WritePro/commands-legacy/wp-get-breaks",
                "WritePro/commands-legacy/wp-get-data-context",
                "WritePro/commands-legacy/wp-get-element-by-id",
                "WritePro/commands-legacy/wp-get-elements",
                "WritePro/commands-legacy/wp-get-footer",
                "WritePro/commands-legacy/wp-get-formulas",
                "WritePro/commands-legacy/wp-get-frame",
                "WritePro/commands-legacy/wp-get-header",
                "WritePro/commands-legacy/wp-get-links",
                "WritePro/commands-legacy/wp-get-page-count",
                "WritePro/commands-legacy/wp-get-position",
                "WritePro/commands-legacy/wp-get-section",
                "WritePro/commands-legacy/wp-get-sections",
                "WritePro/commands-legacy/wp-get-style-sheet",
                "WritePro/commands-legacy/wp-get-style-sheets",
                "WritePro/commands-legacy/wp-get-subsection",
                "WritePro/commands-legacy/wp-get-text",
                "WritePro/commands-legacy/wp-get-view-properties",
                "WritePro/commands/wp-import-document",
                "WritePro/commands-legacy/wp-import-style-sheets",
                "WritePro/commands/wp-insert-break",
                "WritePro/commands/wp-insert-document-body",
                "WritePro/commands/wp-insert-formula",
                "WritePro/commands/wp-insert-picture",
                "WritePro/commands-legacy/wp-insert-table",
                "WritePro/commands-legacy/wp-is-font-style-supported",
                "WritePro/commands-legacy/wp-new",
                "WritePro/commands-legacy/wp-new-bookmark",
                "WritePro/commands-legacy/wp-new-footer",
                "WritePro/commands-legacy/wp-new-header",
                "WritePro/commands-legacy/wp-new-style-sheet",
                "WritePro/commands-legacy/wp-new-subsection",
                "WritePro/commands-legacy/wp-new-text-box",
                "WritePro/commands-legacy/wp-paragraph-range",
                "WritePro/commands-legacy/wp-picture-range",
                "WritePro/commands-legacy/wp-print",
                "WritePro/commands/wp-reset-attributes",
                "WritePro/commands-legacy/wp-select",
                "WritePro/commands-legacy/wp-selection-range",
                "WritePro/commands/wp-set-attributes",
                "WritePro/commands-legacy/wp-set-data-context",
                "WritePro/commands-legacy/wp-set-frame",
                "WritePro/commands-legacy/wp-set-link",
                "WritePro/commands-legacy/wp-set-text",
                "WritePro/commands-legacy/wp-set-view-properties",
                "WritePro/commands/wp-table-append-row",
                "WritePro/commands-legacy/wp-table-delete-columns",
                "WritePro/commands-legacy/wp-table-delete-rows",
                "WritePro/commands-legacy/wp-table-get-cells",
                "WritePro/commands-legacy/wp-table-get-columns",
                "WritePro/commands-legacy/wp-table-get-rows",
                "WritePro/commands-legacy/wp-table-insert-columns",
                "WritePro/commands-legacy/wp-table-insert-rows",
                "WritePro/commands-legacy/wp-table-merge-cells",
                "WritePro/commands-legacy/wp-table-range",
                "WritePro/commands-legacy/wp-table-split-cells",
                "WritePro/commands-legacy/wp-text-range",
                "WritePro/commands-legacy/wp-use-page-setup"
              ]
            }
          ]
        },
       {
          type: "link",
          label: "4D NetKit",
          href: "https://developer.4d.com/4D-NetKit"
        },
        {
          type: "category",
          label: "4D AIKit",
          link: {
            type: "generated-index",
            title: "4D AIKit",
            slug: "/category/4d-aikit",
            keywords: [
              "4D AIKit"
            ],
            image: "/img/docusaurus.png"
          },
          items: [
            "aikit/overview",
            "aikit/asynchronous-call",
            "aikit/compatible-openai",
            {
              type: "category",
              label: "Classes",
              items: [
                "aikit/Classes/openai",
                "aikit/Classes/openaiapiresource",
                "aikit/Classes/openaichatapi",
                "aikit/Classes/openaichatcompletionsapi",
                "aikit/Classes/openaichatcompletionslistparameters",
                "aikit/Classes/openaichatcompletionsmessagesapi",
                "aikit/Classes/openaichatcompletionsmessagesparameters",
                "aikit/Classes/openaichatcompletionsparameters",
                "aikit/Classes/openaichatcompletionsresult",
                "aikit/Classes/openaichatcompletionsstreamresult",
                "aikit/Classes/openaichathelper",
                "aikit/Classes/openaichoice",
                "aikit/Classes/openaiembedding",
                "aikit/Classes/openaiembeddingsapi",
                "aikit/Classes/openaiembeddingsparameters",
                "aikit/Classes/openaiembeddingsresult",
                "aikit/Classes/openaierror",
                "aikit/Classes/openaiimage",
                "aikit/Classes/openaiimageparameters",
                "aikit/Classes/openaiimagesapi",
                "aikit/Classes/openaiimagesresult",
                "aikit/Classes/openaimessage",
                "aikit/Classes/openaimodel",
                "aikit/Classes/openaimodellistresult",
                "aikit/Classes/openaimodelresult",
                "aikit/Classes/openaimodelsapi",
                "aikit/Classes/openaimoderation",
                "aikit/Classes/openaimoderationitem",
                "aikit/Classes/openaimoderationresult",
                "aikit/Classes/openaimoderationsapi",
                "aikit/Classes/openaiparameters",
                "aikit/Classes/openairesult",
                "aikit/Classes/openaitool",
                "aikit/Classes/openaivision",
                "aikit/Classes/openaivisionhelper"
              ]
            }
          ]
        },
        {
          type: "link",
          label: "4D Progress",
          href: "https://github.com/4d/4D-Progress/blob/main/README.md"
        },
        {
          type: "link",
          label: "4D SVG",
          href: "https://developer.4d.com/4D-SVG"
        },
        {
          type: "link",
          label: "4D Widgets",
          href: "https://github.com/4d/4D-Widgets/blob/main/Readme.md"
        },
        {
          type: "link",
          label: "4D QPDF",
          href: "https://github.com/4d/4D-QPDF?tab=readme-ov-file#readme"
        },
        {
          type: "link",
          label: "Go Mobile with 4D",
          href: "https://developer.4d.com/go-mobile/"
        },
        {
          type: "link",
          label: "4D Mobile App Server",
          href: "https://github.com/4d/4D-Mobile-App-Server/blob/main/README.md"
        },
       {
          type: "link",
          label: "4D Mobile App Server",
          href: "https://github.com/4d/4D-Mobile-App-Server/blob/main/README.md"
        },
       {
          type: "link",
          label: "4D Mobile App Server",
          href: "https://github.com/4d/4D-Mobile-App-Server/blob/main/README.md"
        },
       {
          type: "link",
          label: "4D Mobile App Server",
          href: "https://github.com/4d/4D-Mobile-App-Server/blob/main/README.md"
        },
       {
          type: "link",
          label: "4D Mobile App Server",
          href: "https://github.com/4d/4D-Mobile-App-Server/blob/main/README.md"
        },
       {
          type: "link",
          label: "Build4D",
          href: "https://github.com/4d/Build4D"
       }
    ]
    }
  ]
}

