name: build

on:
  pull_request:
    branches: [main]
  push: 
    branches:
      - '*/*'
      - '!main'

jobs:
  check:
    uses: ./.github/workflows/workflow-syntax-check.yml
  build:
    uses: ./.github/workflows/workflow-build.yml
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-build
      cancel-in-progress:  true
  build-static:
    uses: ./.github/workflows/workflow-build-static.yml
