name: Build static documentation

on:
  workflow_call:

jobs:
  language_matrix:
    strategy:
      matrix:
        language: ["en", "fr", "es", "ja", "pt"]
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Build
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build -- --locale ${{ matrix.language }}
        env:
            DOCUSAURUS_LANGUAGE: ${{ matrix.language }}
            DOCUSAURUS_ROUTER: 'hash'
      - uses: actions/upload-artifact@v4
        with:
          path: ./build
          name: build-${{ matrix.language }}
