name: Build static documentation

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        language: ["en", "fr", "es", "ja", "pt"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build
        run: |
          bun install
          bun run build -- --locale ${{ matrix.language }}
        env:
            DOCUSAURUS_LANGUAGE: ${{ matrix.language }}
            DOCUSAURUS_ROUTER: 'hash'
      - uses: actions/upload-artifact@v4
        with:
          path: ./build
          name: static-doc-${{ matrix.language }}
