name: Build documentation

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        language: ["en", "fr", "es", "ja", "pt"]
    runs-on: ubuntu-latest
    steps:
      - name: Get disk space
        run: |
          df -h /
          sudo rm -rf \
          "$AGENT_TOOLSDIRECTORY" \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift
          df -h /
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Build
        env:
          DOCUSAURUS_SSG_WORKER_THREAD_COUNT: 1 # To limit the memory usage
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build -- --locale ${{ matrix.language }}
      - name: Google verification
        run: |
          cd build
          echo "google-site-verification: google1a6263055b2bea44.html" >> google1a6263055b2bea44.html
      - uses: actions/upload-artifact@v4
        with:
          path: ./build
          name: build-${{ matrix.language }}
